version: '3.5'

services:
  # database
  db:
    image: mysql:5.7
    container_name: mysql
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    volumes:
      - db_data:/var/lib/mysql
      - ./create.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:?err}
      MYSQL_DATABASE: ${MYSQL_DATABASE:?err}
      MYSQL_USER: ${MYSQL_USER:?err}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:?err}
    networks:
      - asir
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:?err}
    networks:
      - asir
  caddy:
    depends_on:
      - phpmyadmin
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./caddy:/config
    networks:
      - asir
  # logs
  filebeat:
    image: docker.elastic.co/beats/filebeat:7.16.3
    container_name: filebeat
    user: root
    environment:
      ELASTIC_CLOUD_ID: charlas-teis:ZXUtd2VzdC0xLmF3cy5mb3VuZC5pbyQ3NjM1NjQ0MzY3NzQ0ZDE4OTUxNTFiNDBhYjY0YzNhNyQwZjc0OTUxYmNlM2M0MjVhODM1Zjk3MWU1MDUyMjU5ZA==
      ELASTIC_CLOUD_AUTH: elastic:VFyx2JK5ipNUTV3nJpGNOorJ
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  asir:
    name: 'asir'

volumes:
  db_data:
